
project_id = "agmbptbllklzsswazfwm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
port = 54325

[storage]
enabled = true

[analytics]
enabled = true

[realtime]
enabled = true

[functions]
[functions.ai-chat]
verify_jwt = false
[functions.search-doctors]
verify_jwt = false
